apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-api
  title: Sample API
  description: Sample API catalog entity with TechDocs documentation
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
